Repository Zack-Dx/Twitter-Landing-Page, pull requests merged in 2022-10, with the labels that each got.

#18 height of container fixed
  css/style.css
Labels: ready to merge

#20 added color toggle functionality
  HTML/index.html
  css/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, ready to merge, urgent

#33 update file readme.md (hactoberfest 2022)
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#35 Added Contributors details in Readme file
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#36 Added responsive design
  css/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, ready to merge, urgent

#46 updated twitter logos
  css/style.css
  img/background.png
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#50 2*Updated everything and now its up to date with your repo with all updated code
  README.md
  css/style.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#51 Fix: Css Location
  index.html
  style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#61 Update metas in index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted
